language: php

php:
  - '7.0'
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=ruleset.xml -s ./src

notifications:
  email: false
